### ISSUE TITLE
broken: renew requesting ACME-challenge with certbot 0.10.0

### ISSUE THREAD

**Issue by jelko** [jamesseanwright/certbot-auto-heroku-renewal#1]
Automatic renews don't work for me anymore. certbot is apparently requesting a new ACME response.

I receive this issue when running `renew.sh`:
```
Attempting to renew cert from /etc/letsencrypt/renewal/XXX.conf produced an unexpected error: The manual plugin is not working; there may be problems with your existing configuration.
The error was: PluginError('An authentication script must be provided with --manual-auth-hook when using the manual plugin non-interactively.',). Skipping.
```

Regarding the [issue about this](https://github.com/certbot/certbot/issues/2782#issuecomment-274250727) it is now possible to include a hook into the manual auth process.

Quoting:
```
manual:
  Authenticate through manual configuration or custom shell scripts. When
  using shell scripts, an authenticator script must be provided. The
  environment variables available to this script are $CERTBOT_DOMAIN which
  contains the domain being authenticated, $CERTBOT_VALIDATION which is the
  validation string, and $CERTBOT_TOKEN which is the filename of the
  resource requested when performing an HTTP-01 challenge. An additional
  cleanup script can also be provided and can use the additional variable
  $CERTBOT_AUTH_OUTPUT which contains the stdout output from the auth
  script.

  --manual-auth-hook MANUAL_AUTH_HOOK
                        Path or command to execute for the authentication
                        script (default: None)
  --manual-cleanup-hook MANUAL_CLEANUP_HOOK
                        Path or command to execute for the cleanup script
                        (default: None)
  --manual-public-ip-logging-ok
                        Automatically allows public IP logging (default: Ask)
```

**Comment by jamesseanwright** [comment]
Hey @jelko,

I'm pretty swamped at the moment but I'll hopefully take a look at this in the next couple of weeks. Alternatively, feel free to open a pull request if you figure out the fix.

Cheers,
James

**Comment by lippytak** [comment]
I'm having the same problem (I think?) upon running `certbot renew`:
```
processing /etc/letsencrypt/renewal/CERTNAME
-------------------------------------------------------------------------------
Cert is due for renewal, auto-renewing...
Could not choose appropriate plugin: The manual plugin is not working; there may be problems with your existing configuration.
The error was: PluginError('An authentication script must be provided with --manual-auth-hook when using the manual plugin non-interactively.',)
Attempting to renew cert from /etc/letsencrypt/renewal/CERTNAME.conf produced an unexpected error: The manual plugin is not working; there may be problems with your existing configuration.
The error was: PluginError('An authentication script must be provided with --manual-auth-hook when using the manual plugin non-interactively.',). Skipping.
```

Running certbot version: 0.10.1

Happy to provide more info if helpful. This is the first time I'm trying to renew via certbot.

@jelko have you figured out a solution?

**Comment by jamesseanwright** [comment]
Hey @jelko , @lippytak,

Apologies that I haven't investigated this yet; I've had a million other things going on at the same time.

I have some free time until my next contract begins, so I'll take a look on Friday or Saturday. :smile: 

Cheers,
James

**Comment by jamesseanwright** [comment]
Hey @jelko, @lippytak,

Sorry for the lack of response. I've just successfully renewed my website's certificates after upgrading to certbot-auto 0.14.0. Please could you upgrade and let me know if you are still experiencing this issue?

Cheers,
James

**Comment by jamesseanwright** [comment]
Closing for now due to lack of response. Feel free to reopen this if you're still encountering issues!

**Comment by jelko** [comment]
Hej @jamesseanwright, @lippytak,
sorry for my lack of response. Too many things to do... you know it;)

I just tried to upgrade the certificates, so I did a little bit of digging: `certbot-auto` is not supported on Mac yet. (This means we, or at least I am, stuck with the regular `certbot`.)

`certbot` has a manual mode (which fits, since Heroku is a standard webserver) and offers [hooks](https://certbot.eff.org/docs/using.html#hooks) to implement an automatic behavior.
I just did a little bit of experimentation and build a working version: Check out my [clone](https://github.com/jelko/certbot-heroku-renewal/commit/def6a0cf6b8b6b0483dfc23881a1517143bd88f6).

Have a nice week!

**Comment by jamesseanwright** [comment]
Hey guys!

I see, I wasn't aware of that! In that case, I will rename this repo to `certbot-auto-heroku-renewal` to make this requirement clearer!

Thanks, same to you!

**Comment by jamesseanwright** [comment]
@jelko I've also linked to your fork in the README.

**Comment by jelko** [comment]
Thanks James! I just updated my README as well to reflect the new mechanism for verification.
